### ISSUE TITLE
Sample Code to Demo Abilities of SDK

### ISSUE THREAD

**Issue by JigneshWorld** [localytics/android-samples#1]

**Comment by deRonbrown** [comment]
@JigneshPatel23, can you explain further the abilities for which you would like to see sample code? Our [Android documentation](http://docs.localytics.com/dev/android.html#android) should cover most use cases, but we'd certainly like to know what areas could use more documentation and code samples.

**Comment by JigneshWorld** [comment]
If sample is available then it will help developer to just configure it
with the account and try and see how it helps with real admin access.

Else just for checking thay have to write the sample code from scratch.
So, I think it will just help the developer community.
