### ISSUE TITLE
Handling notifications on sdk v4.4 & greater 

### ISSUE THREAD

**Issue by rohitramkumar308** [localytics/android-samples#2]
Localytics push messaging using FCM.

The documentation states the following:

```
if (data.containsKey("ll"))
      {
        Localytics.displayPushNotification(convertMap(data));
      }
      else
      {
        // The notification is not from Localytics or the Firebase Dashboard
        showNotification(data.get("message"));
      }
```

where as the sample app has this:

       //Use the contents of this method if you are using SDK 4.4 or greater.
            handleNotificationInSDK44(data);

    private void handleNotificationInSDK44(final Map<String, String> data) {
        if (!Localytics.handleFirebaseMessage(data)) {
            showNotification(data.get("message"));
        }
    }
```

Which one is correct ?

**Comment by Mriegel** [comment]
@rohitramkumar308 If you are using SDK 4.4 or greater you can use the second snippet you included: 
```
if (!Localytics.handleFirebaseMessage(data)) {
    showNotification(data.get("message"));
}
```
If you are still using an older SDK version then the first snippet is required.  In SDK 4.4 we added the method `handleFirebaseMessage` to make this integration easier for developers, and remove the need for you to understand how we store the data we send for push messages.

Hope this helps!
