### ISSUE TITLE
Clicking on a notification opens and closes the PushTrackingActivity

### ISSUE THREAD

**Issue by rohitramkumar308** [localytics/android-samples#3]
I have implmented the latest version of localytics v4.4 with FCM.  When clicking on the notification, it opens the PushTrackingActivity and closes it.  How to open a specific activity ?

**Comment by Mriegel** [comment]
@rohitramkumar308 Our docs around this for 4.4 are listed here: https://docs.localytics.com/dev/android.html#custom-push-configuration-building-notifications-v4-android.

If those docs don't provide enough information for you, please feel free to ping our support team at support@localytics.com and they should be able to help you sort out your issues with `PushTrackingActivity`
